### ISSUE TITLE
Alignment of GitHub stats

### ISSUE THREAD

**Issue by animeshbhakat** [ankushKun/ankushKun#4]
"Most used Languages" stat and GitHub stats are looking a bit odd due to having different heights.

![Screenshot (823)](https://user-images.githubusercontent.com/60314168/118084019-91c9d500-b3dd-11eb-8a88-62fbec46e4e6.png)

I think This looks much better.

![Screenshot (826)](https://user-images.githubusercontent.com/60314168/118084039-9c846a00-b3dd-11eb-9401-e9590be86362.png)

**Comment by ankushKun** [comment]
could you please share what changes you made to the elements

**Comment by animeshbhakat** [comment]
Hello @ankushKun.. I think this will help...

<a>
  <img align="center" src="https://github-readme-stats.vercel.app/api?username=ankushKun&show_icons=true&include_all_commits=true&theme=material-palenight" alt="Anurag's github stats" />
</a>
<a>
  <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=ankushKun&layout=compact&theme=material-palenight" height="195px"/>
</a>

**Comment by ankushKun** [comment]
Thank you very much :)
